### ISSUE TITLE
Peer to peer review 23/12/21

### ISSUE THREAD

**Issue by williamrolando88** [Omar-Muhamad/JavaScript-Capston-Project#28]
Hi @keroloussamy and @Omar-Muhamad 

Congratulations on your advance so far 😃. Here I have some suggestion for you:

- In this line of code is unnecessary the use of this expression `[...]`, because you already have the data in form of on an array  in the previous line. https://github.com/Omar-Muhamad/JavaScript-Capston-Project/blob/ba0fbe9d14965bd2a54830120fd5e163bcd55038/src/mealAPI.js#L30-L31 In that way you prevent creating an unnecessary copy of your data.
- For maintainability, it would be better to have this big code separated on different dedicated functions: https://github.com/Omar-Muhamad/JavaScript-Capston-Project/blob/ba0fbe9d14965bd2a54830120fd5e163bcd55038/src/mealAPI.js#L11-L35

Happy coding 🍀

**Comment by keroloussamy** [comment]
Thanks, @williamrolando88 😃
